safe: true
# GitHub Pages only works in the root directory.
source: .
destination: ./_site
lsi: false
paginate: 1000
highlighter: pygments
permalink: /p/:title/
baseurl: "https://blog.bekt.net"

collections:
  pages:
    output: true
